#!/bin/bash

echo "=========================================="
echo "장애인 직원 사이드바 메뉴 테스트"
echo "=========================================="
echo ""

# Login as emp01
echo "🔐 박영희 (01099990001) 로그인 중..."
TOKEN=$(curl -s -X POST https://jangpyosa.com/api/auth/login \
  -H "Content-Type: application/json" \
  -d '{"identifier":"01099990001","password":"test1234"}' | jq -r '.accessToken')

if [ "$TOKEN" != "null" ] && [ -n "$TOKEN" ]; then
  echo "✅ 로그인 성공!"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "📱 브라우저에서 테스트하세요:"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "1️⃣  로그인 페이지: https://jangpyosa.com/employee/login"
  echo "    전화번호: 01099990001"
  echo "    비밀번호: test1234"
  echo ""
  echo "2️⃣  로그인 후 사이드바에서 다음 메뉴 확인:"
  echo ""
  echo "    ✅ 직원 메뉴"
  echo "       1. ⏰ 출퇴근 관리   (/employee/attendance)"
  echo "       2. 📋 업무 관리     (/employee/work-orders) ⭐ NEW"
  echo "       3. 🏖️ 휴가 신청     (/employee/leave)"
  echo ""
  echo "3️⃣  다음 메뉴는 숨겨져야 합니다:"
  echo "    ❌ 장애인직원관리솔루션"
  echo "    ❌ 고용부담금감면계산기"
  echo "    ❌ 연계고용감면센터"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "🧪 업무 관리 페이지 기능:"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "✓ 나에게 할당된 업무지시 목록 조회"
  echo "✓ 업무 긴급도 확인 (긴급/높음/보통/낮음)"
  echo "✓ 업무 상태 확인 (대기중/진행중/완료)"
  echo "✓ 음성 읽기 기능 (TTS)"
  echo "✓ 완료 보고서 작성 및 제출"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "📝 테스트 계정:"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "주식회사 페마연:"
  echo "  박영희: 01099990001 / test1234"
  echo "  이철수: 01099990002 / test1234"
  echo "  정미라: 01099990003 / test1234"
  echo ""
  echo "공공기관1:"
  echo "  최동욱: 01099990004 / test1234"
  echo "  한수진: 01099990005 / test1234"
  echo ""
  echo "교육청1:"
  echo "  김민서: 01099990006 / test1234"
  echo ""
else
  echo "❌ 로그인 실패"
fi
